version: '3.8'
services:
  sqlserver_app_web:
   image: mcr.microsoft.com/mssql/server:2022-latest
   container_name: bd_veterinario
   restart: always
   environment:
    MSSQL_SA_PASSWORD: Password2025
    MSSQL_PID: Express
    ACCEPT_EULA: Y
   volumes:
     - C:/Users/elfla/Documents/Docker/Volumenes/sqlserver_chato:/var/opt/mssql/data
   ports:
    - 1407:1433